### ISSUE TITLE
Expand the model for feature-completion

### ISSUE THREAD

**Issue by pszi** [AMIOL7/ELME#38]
Kindly request the following methods implemented in the model:

- bool checkForCycle(Node origin) : called immediately after link connection, if returns true (meaning it finds a cycle in the graph) the newly created connection is undone immediately after that, preventing the need for an graph flow update trigger. Important to keep passing the origin node down into other calls of the same method pseudo-recursively
-  void triggerUpdate() called when the the graph changed in a way that has an effect on the final output(s)

**Comment by vismate** [comment]
These methods could be implemented on ```Node```s themselves, since they do not require any more than relationships between nodes. I think it would be much more ergonomic this way.

The ```checkForCycle()``` method would check if the node it was called on is in a cycle or not, the ```triggerUpdate()``` method would trigger an update down the line from the given node.

What do you think?

**Comment by vismate** [comment]
Request has been received and implemented in linked branch. If @pszi agrees we can close this issue, and continue the discussion in issue #35 to avoid duplication.
_(if you (@pszi) agree, may go ahead and close the issue right ahead )_

**Comment by pszi** [comment]
Okay.
